import{Brain,Database,FileText,ShieldCheck}from"lucide-react";
import{useTwinStore}from"../store/twinStore";
import{pretty,pct}from"./ui";
import{Bar,PageHeader,Panel,PanelTitle,StatusPill}from"./ReferenceUI";

export default function DiagnosticsDeck(){
 const twin=useTwinStore(s=>s.twin),ai=twin?.ai,r=twin?.residuals??{},tr=twin?.trends??{},trust=twin?.sensor_trust??{},fault=ai?.anomaly?pretty(ai.probable_fault):"Normal Operation",confidence=Number(ai?.fault_confidence??twin?.confidence.decision??86),sev=(twin?.health.overall??96)<65?"HIGH":(twin?.health.overall??96)<86?"MODERATE":"LOW";
 const contrib=(ai?.evidence?.length?ai.evidence.slice(0,6):[{feature:"oil_pressure_residual",weight:.34,value:Number(r.oil_pressure??0)},{feature:"pressure_decline",weight:.22,value:Number(tr.oil_pressure_per_min??-4.1)},{feature:"oil_temperature",weight:.18,value:Number(r.oil_temperature??0)},{feature:"vibration_increase",weight:.14,value:Number(r.vibration??0)},{feature:"persistence",weight:.08,value:Number(ai?.anomaly_persistence_samples??0)},{feature:"sensor_trust",weight:.04,value:Number(twin?.confidence.sensor??90)}]);
 const evidence=[`Oil pressure is ${Math.abs(Math.round(Number(r.oil_pressure??-.2)*100))}% below the expected value for the current operating condition.`,`Consistent ${Number(tr.oil_pressure_per_min??-4.1)<0?"downward":"abnormal"} pressure trend at ${Math.abs(Number(tr.oil_pressure_per_min??-4.1)).toFixed(1)} kPa/min.`,`Oil temperature is ${Math.abs(Number(r.oil_temperature??5)).toFixed(1)}°C ${Number(r.oil_temperature??5)>=0?"higher":"lower"} than expected.`,`Vibration shows sustained deviation of ${Math.abs(Number(r.vibration??.08)).toFixed(2)} g.`,`Deviation has persisted across multiple samples, reducing the likelihood of transient noise.`];
 return <div className="ref-page diagnostics-ref-page"><PageHeader title="Diagnostics & Explainability" subtitle="Deep insights into AI decisions, model behavior, sensor trust, and system explainability"/>
  <div className="ref-tabs"><button className="active">Why This Diagnosis?</button><button>Model Analysis</button><button>Sensor Trust</button><button>Data Quality</button><button>System Status</button></div>
  <div className="diag-grid">
   <Panel><PanelTitle icon={<FileText/>} title="Diagnosis Breakdown"/><div className={`diagnosis-card ${ai?.anomaly?"bad":"good"}`}><span>Current Diagnosis</span><b>{fault}</b></div><div className="diag-pair"><div><span>Confidence</span><b>{Math.round(confidence)}%</b><Bar value={confidence} color="blue"/></div><div><span>Severity</span><StatusPill tone={sev==="LOW"?"green":sev==="MODERATE"?"orange":"red"}>{sev}</StatusPill></div></div><h4>Top Contributing Signals</h4><div className="contrib-list diag-contrib">{contrib.map(x=><div key={x.feature}><span>{pretty(x.feature)}</span><Bar value={Math.min(100,Math.max(2,x.weight*100*2.3))} color="blue"/><b>{Math.round(x.weight*100)}%</b></div>)}</div></Panel>
   <Panel><PanelTitle title="Evidence Explanation"/><div className="numbered-evidence">{evidence.map((x,i)=><div key={x}><i>{i+1}</i><p>{x}</p></div>)}</div><div className="model-reasoning"><Brain/><div><b>Model Reasoning</b><p>{ai?.anomaly?"Multiple correlated signals indicate a developing engine-system degradation rather than a transient anomaly. The decision combines residual magnitude, persistence, cross-sensor consistency and the current operating state.":"Current residuals remain inside the synthetic demonstrator's nominal operating envelope. No persistent correlated degradation pattern is active."}</p></div></div></Panel>
   <div className="diag-right"><Panel><PanelTitle icon={<Database/>} title="Sensor Trust"/><div className="trust-list">{[["RPM",trust.rpm??99],["CHT",trust.cht??97],["EGT",trust.egt??96],["Oil Pressure",trust.oil_pressure??92],["Oil Temp",trust.oil_temperature??90],["Vibration",trust.vibration??90],["Battery",trust.battery_voltage??89]].map(([k,v])=><div key={String(k)}><span>{k}</span><Bar value={Number(v)}/><b>{Math.round(Number(v))}%</b></div>)}</div></Panel><Panel><PanelTitle icon={<ShieldCheck/>} title="Runtime Information"/><div className="runtime-list"><div><span>Model Mode</span><b>{pretty(ai?.model_state??"engineering fallback")}</b></div><div><span>Model Source</span><b>Synthetic Training Data</b></div><div><span>Validation Scope</span><b>{pretty(ai?.validation_scope??"engineering demonstrator")}</b></div><div><span>Fallback Mode</span><b>{ai?.model_warning?"Rule-based + consistency":"Available"}</b></div></div></Panel></div>
  </div>
 </div>
}
