import{Canvas,useFrame}from"@react-three/fiber";import{Html,OrbitControls,useGLTF}from"@react-three/drei";import{Focus,Maximize2,Minimize2,Move3d,RotateCcw,Scan,ZoomIn,ZoomOut}from"lucide-react";import{Suspense,useEffect,useMemo,useRef,useState}from"react";import*as THREE from"three";import type{Object3D}from"three";
import{useTwinStore}from"../store/twinStore";import{supportsWebGL}from"../utils/webgl";import{fmt,pretty}from"./ui";

type Props={compact?:boolean;explode?:boolean;xray?:boolean;focus?:string;autoRotate?:boolean;zoom?:number;resetToken?:number;onFocus?:(s:string)=>void};
type ViewMode="assembled"|"exploded"|"xray";type ModuleName="core"|"cylinders"|"injection"|"turbo"|"cooling"|"lubrication"|"internals";
const MODULES:ModuleName[]=["core","cylinders","injection","turbo","cooling","lubrication","internals"];
const OFFSETS:Record<ModuleName,[number,number,number]>={core:[0,0,0],cylinders:[.95,.1,0],injection:[0,.85,.08],turbo:[0,-.15,1],cooling:[-.75,.45,-.3],lubrication:[0,-.75,-.1],internals:[-.85,-.05,.15]};
const LABELS:Record<ModuleName,string>={core:"Crankcase",cylinders:"Cylinder banks",injection:"Fuel injection",turbo:"Turbocharger",cooling:"Cooling circuit",lubrication:"Lubrication",internals:"Internal drive"};
function healthFor(module:ModuleName,t:any){if(!t)return 96;if(module==="cylinders"||module==="cooling")return Number(t.health?.thermal??96);if(module==="lubrication")return Number(t.health?.lubrication??96);if(module==="injection"||module==="turbo")return Number(t.health?.combustion??96);return Number(t.health?.mechanical??96)}
function faultModule(fault?:string):ModuleName{const f=(fault||"").toLowerCase();if(f.includes("oil")||f.includes("lubric"))return"lubrication";if(f.includes("cool")||f.includes("heat")||f.includes("thermal"))return"cooling";if(f.includes("inject")||f.includes("combust")||f.includes("misfire"))return"injection";if(f.includes("turbo"))return"turbo";if(f.includes("vibr")||f.includes("mechan"))return"internals";return"core"}

function EngineAsset({mode,opacity,focus,onFocus}:{mode:ViewMode;opacity:number;focus:string;onFocus:(m:string)=>void}){
 const gltf=useGLTF("/assets/engine/twinguard-rotax-915-production.glb"),root=useMemo(()=>gltf.scene.clone(true),[gltf.scene]),modules=useRef<Array<{name:ModuleName;object:Object3D;base:THREE.Vector3}>>([]);
 useEffect(()=>{modules.current=[];root.traverse(o=>{const n=o.name.toLowerCase() as ModuleName;if(MODULES.includes(n)){if(!o.userData.tgBase)o.userData.tgBase=o.position.clone();modules.current.push({name:n,object:o,base:o.userData.tgBase.clone()})}if((o as THREE.Mesh).isMesh){const mesh=o as THREE.Mesh;mesh.castShadow=true;mesh.receiveShadow=true;mesh.material=Array.isArray(mesh.material)?mesh.material.map(m=>m.clone()):mesh.material.clone()}})},[root]);
 useEffect(()=>{root.traverse(o=>{if(!(o as THREE.Mesh).isMesh)return;const mesh=o as THREE.Mesh,mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];const owner=MODULES.find(m=>{let p:Object3D|null=o;while(p){if(p.name.toLowerCase()===m)return true;p=p.parent}return false}),selected=focus!=="all"&&owner===focus;for(const m of mats){m.transparent=mode==="xray"||opacity<.99;m.opacity=mode==="xray"?(selected?Math.max(.5,opacity):Math.min(.32,opacity)):opacity;m.depthWrite=m.opacity>.55;m.needsUpdate=true}})},[root,mode,opacity,focus]);
 useFrame((_,dt)=>{const k=1-Math.exp(-dt*5.5);for(const item of modules.current){const v=mode==="exploded"?OFFSETS[item.name]:[0,0,0],target=item.base.clone().add(new THREE.Vector3(...v));item.object.position.lerp(target,k)}});
 return <group rotation={[.08,-.48,.02]} scale={1.12} onDoubleClick={e=>{e.stopPropagation();let p:Object3D|null=e.object;while(p&&!MODULES.includes(p.name.toLowerCase() as ModuleName))p=p.parent;onFocus(p?.name.toLowerCase()||"all")}}><primitive object={root}/></group>
}
function FaultMarker({module,active}:{module:ModuleName;active:boolean}){if(!active)return null;const p=OFFSETS[module];return <group position={[p[0]*.35,p[1]*.35+.35,p[2]*.35]}><mesh><sphereGeometry args={[.12,24,24]}/><meshBasicMaterial color="#ef4444" toneMapped={false}/></mesh><Html center distanceFactor={8}><div className="engine-fault-label"><i/>FAULT LOCATION</div></Html></group>}
function Loader(){return <Html center><div className="engine-loader"><i/><span>Loading engineering model…</span></div></Html>}
function Scene({mode,opacity,focus,autoRotate,resetToken,onFocus,fault}:{mode:ViewMode;opacity:number;focus:string;autoRotate:boolean;resetToken:number;onFocus:(m:string)=>void;fault:ModuleName}){const controls=useRef<any>();useEffect(()=>{controls.current?.reset()},[resetToken]);return <><color attach="background" args={["#f4f8fb"]}/><hemisphereLight args={["#ffffff","#b9cad6",2.4]}/><directionalLight position={[5,8,6]} intensity={3.2} castShadow/><directionalLight position={[-6,2,-4]} intensity={1.6} color="#93c5fd"/><Suspense fallback={<Loader/>}><EngineAsset mode={mode} opacity={opacity} focus={focus} onFocus={onFocus}/><FaultMarker module={fault} active={mode==="xray"}/></Suspense><gridHelper args={[16,32,"#c7d8e5","#e5edf3"]} position={[0,-2.25,0]}/><OrbitControls ref={controls} makeDefault target={[0,0,0]} enableDamping dampingFactor={.07} minDistance={4} maxDistance={14} autoRotate={autoRotate} autoRotateSpeed={.6}/></>}

export default function EngineTwin({compact=false,explode=false,xray=false,focus:externalFocus="all",autoRotate:externalRotate=false,resetToken=0,onFocus}:Props){
 const twin=useTwinStore(s=>s.twin),host=useRef<HTMLDivElement>(null),[mode,setMode]=useState<ViewMode>(xray?"xray":explode?"exploded":"assembled"),[opacity,setOpacity]=useState(100),[focus,setFocus]=useState(externalFocus),[autoRotate,setAutoRotate]=useState(externalRotate),[fullscreen,setFullscreen]=useState(false),[reset,setReset]=useState(0);
 useEffect(()=>setFocus(externalFocus),[externalFocus]);useEffect(()=>setMode(xray?"xray":explode?"exploded":"assembled"),[xray,explode]);useEffect(()=>{const fn=()=>setFullscreen(document.fullscreenElement===host.current);document.addEventListener("fullscreenchange",fn);return()=>document.removeEventListener("fullscreenchange",fn)},[]);
 if(typeof document!=="undefined"&&!supportsWebGL())return <div className="webgl-fallback"><strong>3D engine viewer unavailable</strong><span>Enable browser hardware acceleration and reload.</span></div>;
 const fault=faultModule(twin?.ai.probable_fault),setSelected=(m:string)=>{setFocus(m);onFocus?.(m)},toggleFull=async()=>{if(!host.current)return;if(document.fullscreenElement)await document.exitFullscreen();else await host.current.requestFullscreen()};
 return <div ref={host} className={"engine-viewer "+(compact?"compact ":"")+(fullscreen?"fullscreen":"")}><div className="engine-toolbar" role="toolbar" aria-label="3D engine controls"><div className="engine-mode-switch"><button className={mode==="assembled"?"active":""} onClick={()=>setMode("assembled")}>Assembled</button><button className={mode==="exploded"?"active":""} onClick={()=>setMode("exploded")}><Move3d/> Exploded</button><button className={mode==="xray"?"active":""} onClick={()=>setMode("xray")}><Scan/> X-ray</button></div><div className="engine-tool-actions"><button className={autoRotate?"active":""} onClick={()=>setAutoRotate(v=>!v)} title="Auto rotate"><RotateCcw/></button><button onClick={()=>setReset(v=>v+1)} title="Reset camera"><Focus/></button><button onClick={toggleFull} title={fullscreen?"Exit full screen":"Full screen"}>{fullscreen?<Minimize2/>:<Maximize2/>}</button></div></div>
  <div className="engine-canvas"><Canvas shadows dpr={[1,1.6]} camera={{position:[6.8,3.6,8.6],fov:32,near:.1,far:100}} gl={{antialias:true,powerPreference:"high-performance"}}><Scene mode={mode} opacity={opacity/100} focus={focus} autoRotate={autoRotate} resetToken={reset+resetToken} onFocus={setSelected} fault={fault}/></Canvas></div>
  <div className="engine-opacity"><ZoomOut/><label><span>Casing opacity</span><input aria-label="Engine casing opacity" type="range" min="8" max="100" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><b>{opacity}%</b><ZoomIn/></div>
  {!compact&&<div className="engine-parts">{MODULES.map(m=><button key={m} className={focus===m?"active":""} onClick={()=>setSelected(focus===m?"all":m)}><i style={{background:healthFor(m,twin)<86?"#f59e0b":"#20a47b"}}/><span>{LABELS[m]}</span><b>{fmt(healthFor(m,twin),0)}%</b></button>)}</div>}
  {fullscreen&&<aside className="engine-diagnostic-drawer"><small>LIVE DIAGNOSTIC</small><h3>{twin?.ai.anomaly?pretty(twin.ai.probable_fault):"Engine operating normally"}</h3><div className="engine-health-ring"><b>{fmt(twin?.health.overall,0)}%</b><span>overall health</span></div><dl><div><dt>RPM</dt><dd>{fmt(twin?.telemetry.rpm,0)}</dd></div><div><dt>Oil pressure</dt><dd>{fmt(Number(twin?.telemetry.oil_pressure||0)*100,1)} kPa</dd></div><div><dt>CHT</dt><dd>{fmt(twin?.telemetry.cht,1)} °C</dd></div><div><dt>RUL</dt><dd>{fmt(twin?.ai.rul_hours,1)} h</dd></div></dl><p>{mode==="xray"?"Fault marker stays visible through transparent casing.":"Switch to X-ray to inspect the predicted fault location."}</p></aside>}</div>
}
useGLTF.preload("/assets/engine/twinguard-rotax-915-production.glb");
