import{AlertTriangle,Activity,BatteryCharging,Droplets,Fuel,Thermometer}from"lucide-react";
import{useTwinStore}from"../store/twinStore";
import{fmt,pretty}from"./ui";
import{Bar,EngineeringReadout,PageHeader,Panel,PanelTitle,Ring,StatusPill}from"./ReferenceUI";

export default function HealthFaultsDeck(){
 const twin=useTwinStore(s=>s.twin),h=twin?.health,ai=twin?.ai,r=twin?.residuals??{},tr=twin?.trends??{},trust=twin?.sensor_trust??{},t=twin?.telemetry??{};
 const fault=ai?.anomaly?pretty(ai.probable_fault):"Normal Operation",severity=(h?.overall??96)<65?"High":(h?.overall??96)<86?"Moderate":"Low",confidence=Number(ai?.fault_confidence??twin?.confidence.decision??86),persistent=Math.max(0,Number(ai?.anomaly_persistence_samples??0));
 const healths=[["Overall",h?.overall??84,`RUL ${fmt(ai?.rul_hours,1)} h`],["Thermal",h?.thermal??88,`CHT ${fmt(t.cht,1)} °C`],["Lubrication",h?.lubrication??68,`Oil ${fmt(Number(t.oil_pressure??0)*100,1)} kPa`],["Combustion",h?.combustion??92,`Fuel ${fmt(t.fuel_flow,2)} L/h`],["Mechanical",h?.mechanical??81,`Vib ${fmt(t.vibration,3)} g`],["Electrical",h?.electrical??96,`${fmt(t.battery_voltage,2)} V`],["Sensors",h?.sensor??93,`Trust ${fmt(twin?.confidence.sensor,1)}%`]] as const;
 const evidence=[["Oil pressure residual",`${Number(r.oil_pressure??0)*100>=0?"+":""}${fmt(Number(r.oil_pressure??0)*100,1)} kPa`],["Pressure decline rate",`${fmt(Number(tr.oil_pressure_per_min??tr.oil_pressure_rate??0),2)} kPa/min`],["Oil temperature residual",`${Number(r.oil_temperature??0)>=0?"+":""}${fmt(r.oil_temperature,1)} °C`],["Vibration residual",`${Number(r.vibration??0)>=0?"+":""}${fmt(r.vibration,3)} g`],["Persistence",`${persistent} samples`]];
 const now=new Date(twin?.timestamp??Date.now()),ago=(sec:number)=>new Date(now.getTime()-sec*1000).toLocaleTimeString([],{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"});
 const timeline=ai?.anomaly?[[ago(Math.max(45,persistent+35)),"Normal operation",""],[ago(Math.max(30,persistent+15)),"Residual envelope crossed","orange"],[ago(Math.max(15,persistent)),`Diagnosis: ${fault}`,"red"],[ago(5),`Severity: ${severity}`,severity==="High"?"red":"orange"],[ago(0),`Mission state: ${(h?.overall??96)<70?"HIGH":(h?.overall??96)<86?"MEDIUM":"LOW"}`,"orange"]]:[[ago(60),"Normal operation",""],[ago(30),"Twin synchronized",""],[ago(0),"No persistent fault detected","green"]];
 const contrib=(ai?.evidence?.length?ai.evidence.slice(0,5).map(x=>[pretty(x.feature),Math.round(Math.max(0,Math.min(100,x.weight*100)))]):[["Residual Magnitude",40],["Persistence",25],["Degradation Rate",18],["Cross-Sensor Agreement",12],["Sensor Trust",5]]) as Array<[string,number]>;
 return <div className="ref-page health-page"><PageHeader title="Health & Faults" subtitle="Diagnosis, exact evidence, subsystem health, measured state and sensor trust"/>
  <div className="health-top">
   <Panel><PanelTitle title="Current Diagnosis"/><div className={`diagnosis-title ${ai?.anomaly?"bad":"good"}`}><AlertTriangle/><b>{fault}</b></div><div className="kv-list"><div><span>Severity:</span><StatusPill tone={severity==="Low"?"green":severity==="Moderate"?"orange":"red"}>{severity}</StatusPill></div><div><span>Confidence:</span><b>{fmt(confidence,1)}%</b></div><div><span>Anomaly score:</span><b>{fmt((ai?.anomaly_score??0)*100,2)}%</b></div><div><span>Persistence:</span><b>{persistent} samples</b></div></div></Panel>
   <Panel><PanelTitle title="Supporting Evidence"/><div className="evidence-list">{evidence.map(([k,v],i)=><div key={k}><i className={i<2?"red":i<4?"orange":"blue"}/><span>{k}:</span><b>{v}</b></div>)}</div></Panel>
   <Panel><PanelTitle title="Fault Timeline"/><div className="fault-timeline">{timeline.map(([time,label,tone],i)=><div key={i}><i className={String(tone)}/><time>{time}</time><span>{label}</span></div>)}</div></Panel>
  </div>
  <Panel className="health-rings"><PanelTitle title="Subsystem Health" subtitle="Percentage index plus the exact measured engineering state that supports each subsystem"/><div className="rings-row">{healths.map(([name,v,detail],i)=><Ring key={name} value={Number(v)} label={name} detail={detail} delta={i===0&&Number(v)<90?`${fmt(Number(v)-100,1)} pts`:undefined}/>)}</div></Panel>
  <Panel><PanelTitle title="Measured Engineering State" subtitle="Raw live values — not normalized percentages"/><div className="engineering-grid health-engineering-grid"><EngineeringReadout label="Cylinder Head Temp" value={fmt(t.cht,1)} unit="°C" expected={`${fmt(twin?.expected.cht,1)} °C`} residual={`${Number(r.cht??0)>=0?"+":""}${fmt(r.cht,1)} °C`} tone={Math.abs(Number(r.cht??0))>15?"orange":"blue"}/><EngineeringReadout label="Exhaust Gas Temp" value={fmt(t.egt,1)} unit="°C" expected={`${fmt(twin?.expected.egt,1)} °C`} residual={`${Number(r.egt??0)>=0?"+":""}${fmt(r.egt,1)} °C`}/><EngineeringReadout label="Oil Pressure" value={fmt(Number(t.oil_pressure??0)*100,1)} unit="kPa" expected={`${fmt(Number(twin?.expected.oil_pressure??0)*100,1)} kPa`} residual={`${Number(r.oil_pressure??0)>=0?"+":""}${fmt(Number(r.oil_pressure??0)*100,1)} kPa`} tone={Number(r.oil_pressure??0)<-.25?"red":"blue"}/><EngineeringReadout label="Oil Temperature" value={fmt(t.oil_temperature,1)} unit="°C" expected={`${fmt(twin?.expected.oil_temperature,1)} °C`} residual={`${Number(r.oil_temperature??0)>=0?"+":""}${fmt(r.oil_temperature,1)} °C`}/><EngineeringReadout label="Vibration RMS" value={fmt(t.vibration,3)} unit="g" expected={`${fmt(twin?.expected.vibration,3)} g`} residual={`${Number(r.vibration??0)>=0?"+":""}${fmt(r.vibration,3)} g`} tone={Number(r.vibration??0)>.12?"orange":"blue"}/><EngineeringReadout label="Fuel Flow" value={fmt(t.fuel_flow,2)} unit="L/h"/><EngineeringReadout label="Battery Voltage" value={fmt(t.battery_voltage,2)} unit="V"/><EngineeringReadout label="Alternator Voltage" value={fmt(t.alternator_voltage,2)} unit="V"/></div></Panel>
  <div className="health-bottom">
   <Panel><PanelTitle title="Health Contribution Factors"/><div className="contrib-list">{contrib.map(([k,v])=><div key={k}><span>{k}</span><Bar value={Number(v)*2.2} color="blue"/><b>{v}%</b></div>)}</div></Panel>
   <Panel><PanelTitle title="Sensor Trust"/><div className="trust-list">{[["RPM",trust.rpm??99],["CHT",trust.cht??97],["EGT",trust.egt??96],["Oil Pressure",trust.oil_pressure??92],["Oil Temp",trust.oil_temperature??90],["Vibration",trust.vibration??89],["Battery",trust.battery_voltage??91]].map(([k,v])=><div key={String(k)}><span>{k}</span><Bar value={Number(v)} /><b>{fmt(v,1)}%</b></div>)}</div></Panel>
  </div>
 </div>
}
