import{motion}from"framer-motion";
import{AlertTriangle,CheckCircle2,ShieldCheck,Stethoscope,Wrench,Zap}from"lucide-react";
import{useTwinStore}from"../store/twinStore";
import{Badge,Card,Progress,Ring,SectionTitle,fmt,pct,pretty}from"./ui";

const label=(s:string)=>pretty(s.replace(/_residual$/," residual"));
const ringTone=(v:number):"good"|"warn"|"bad"=>v>=88?"good":v>=70?"warn":"bad";
export default function HealthFaultsDeck(){
 const twin=useTwinStore(s=>s.twin),fault=twin?.ai.probable_fault??"normal",anomaly=Boolean(twin?.ai.anomaly),health=twin?.health,evidence=(twin?.ai.evidence??[]).slice(0,5),trust=Object.entries(twin?.sensor_trust??{}),systems=["overall","thermal","lubrication","combustion","mechanical","electrical","sensor"] as const;
 return <motion.div className="premium-page health-page-v2" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>
  <div className="premium-page-head"><div><span>HEALTH INTELLIGENCE</span><h1>Health & Faults</h1><p>Diagnosis, supporting evidence, subsystem health, Sensor Trust and maintenance guidance.</p></div><Badge kind={anomaly?"warn":"good"}>{anomaly?<AlertTriangle size={13}/>:<CheckCircle2 size={13}/>} {anomaly?"DEGRADATION DETECTED":"NOMINAL"}</Badge></div>
  <div className="health-top-grid">
   <Card className="diagnosis-card"><SectionTitle eyebrow="CURRENT DIAGNOSIS" title={anomaly?pretty(fault):"Normal Operation"}/><div className={`diagnosis-icon ${anomaly?"warn":"good"}`}>{anomaly?<Stethoscope/>:<ShieldCheck/>}</div><dl><div><dt>Severity</dt><dd><Badge kind={anomaly?(health?.overall??100)<70?"bad":"warn":"good"}>{anomaly?(health?.overall??100)<70?"High":"Moderate":"None"}</Badge></dd></div><div><dt>Diagnostic Confidence</dt><dd>{pct(twin?.ai.fault_confidence)}</dd></div><div><dt>Status</dt><dd>{anomaly?`Persistent (${twin?.ai.anomaly_persistence_samples??0} samples)`:"Stable"}</dd></div></dl></Card>
   <Card className="supporting-evidence-card"><SectionTitle eyebrow="SUPPORTING EVIDENCE" title="Why TwinGuard raised this state"/><div className="evidence-list-v2">{evidence.length?evidence.map((e,i)=><div key={`${e.feature}-${i}`}><i className={i<2?"hot":""}/><span>{label(e.feature)}</span><strong>{fmt(e.value,Math.abs(e.value)<1?3:1)}</strong></div>):<div className="nominal-evidence"><CheckCircle2/>Residuals remain within the current synthetic healthy envelope.</div>}</div></Card>
   <Card className="fault-timeline-card"><SectionTitle eyebrow="FAULT TIMELINE" title="Current evidence progression"/><div className="vertical-timeline"><div><i className="good"/><span>State synchronization</span><b>Active</b></div><div><i/><span>Residual deviation</span><b>{anomaly?"Detected":"Nominal"}</b></div><div><i className={anomaly?"warn":"good"}/><span>Diagnostic hypothesis</span><b>{anomaly?pretty(fault):"None"}</b></div><div><i className={anomaly?"warn":"good"}/><span>Persistence</span><b>{twin?.ai.anomaly_persistence_samples??0} samples</b></div><div><i className={(health?.overall??100)<75?"bad":anomaly?"warn":"good"}/><span>Health impact</span><b>{pct(health?.overall)}</b></div></div></Card>
  </div>
  <Card className="subsystem-health-card"><SectionTitle eyebrow="SUBSYSTEM HEALTH" title="Engineering health decomposition"/><div className="health-rings-v2">{systems.map(k=>{const v=Number(health?.[k]??0);return <div key={k}><Ring value={v} label={pretty(k)} toneName={ringTone(v)}/>{k==="overall"&&<small>Composite</small>}</div>})}</div></Card>
  <div className="health-bottom-grid">
   <Card><SectionTitle eyebrow="HEALTH CONTRIBUTION FACTORS" title="What is pulling the index down?"/><div className="contribution-bars">{[["Residual Magnitude",Math.min(100,Math.abs(Number(twin?.residuals.oil_pressure??0))*42+Math.abs(Number(twin?.residuals.cht??0))*1.1)],["Persistence",Math.min(100,(twin?.ai.anomaly_persistence_samples??0)*2.4)],["Degradation Rate",anomaly?52:7],["Corroboration",Math.min(100,(twin?.confidence.physics_agreement??0))],["Sensor Trust",100-(twin?.confidence.sensor??100)]].map(([k,v])=><div key={String(k)}><span>{k}</span><Progress value={Number(v)} kind={Number(v)>70?"warn":"blue"}/><b>{fmt(v,0)}%</b></div>)}</div></Card>
   <Card><SectionTitle eyebrow="SENSOR TRUST" title="Channel confidence"/><div className="sensor-trust-v2">{trust.slice(0,8).map(([k,v])=><div key={k}><span>{pretty(k)}</span><Progress value={Number(v)} kind={Number(v)<70?"bad":Number(v)<88?"warn":"good"}/><b>{pct(v)}</b></div>)}</div></Card>
   <Card className="maintenance-card-v2"><SectionTitle eyebrow="MAINTENANCE GUIDANCE" title="Evidence-led next checks" action={<Badge kind={anomaly?"warn":"good"}><Wrench size={12}/>{pretty(twin?.maintenance.priority??"waiting")}</Badge>}/><div className="maintenance-summary"><div><span>Affected subsystem</span><strong>{pretty(twin?.maintenance.affected_subsystem??"--")}</strong></div><div><span>Next mission suitability</span><strong>{pretty(twin?.maintenance.next_mission_suitability??"--")}</strong></div></div><p>{twin?.maintenance.reason??"Awaiting synchronized state."}</p><div className="check-list">{(twin?.maintenance.recommended_checks??[]).map((x,i)=><div key={x}><span>{i+1}</span><CheckCircle2/>{x}</div>)}</div></Card>
  </div>
  <Card className="health-boundary-note"><Zap/><div><strong>Interpretation boundary</strong><p>Health indices, confidence scores and maintenance guidance are proof-of-concept engineering outputs. They are not certified airworthiness or maintenance-release decisions.</p></div><Badge kind="blue">{pretty(twin?.ai.validation_scope??"Synthetic POC")}</Badge></Card>
 </motion.div>
}
