import{Info,Leaf,Play,Route,ShieldCheck}from"lucide-react";
import{useMemo,useState}from"react";
import{analyzeMission}from"../services/twinApi";
import{useTwinStore}from"../store/twinStore";
import type{MissionResult}from"../types/twin";
import{fmt,pretty}from"./ui";
import{EngineeringReadout,PageHeader,Panel,PanelTitle,Ring,StatusPill}from"./ReferenceUI";

type MissionTab="evaluation"|"whatif"|"planner";
export default function MissionDeck(){
 const twin=useTwinStore(s=>s.twin),addMission=useTwinStore(s=>s.addMission),[tab,setTab]=useState<MissionTab>("evaluation"),[type,setType]=useState("endurance"),[duration,setDuration]=useState(8),[altitude,setAltitude]=useState(6000),[temp,setTemp]=useState(-5),[throttle,setThrottle]=useState(70),[load,setLoad]=useState("Medium"),[result,setResult]=useState<MissionResult>(),[baseline,setBaseline]=useState<MissionResult>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const payload=(overrides:Record<string,unknown>={})=>({mission_type:type,duration_hours:duration,cruise_altitude_m:altitude,ambient_temp_c:temp,average_throttle_pct:throttle,load_class:load.toLowerCase(),...overrides});
 const execute=async(p=payload(),preserveBaseline=true)=>{setBusy(true);setError("");try{const r=await analyzeMission(p);setResult(r);if(preserveBaseline)setBaseline(r);addMission(twin?.ai.probable_fault??"normal",r);return r}catch(e:any){setError(e?.response?.data?.detail??e?.message??"Mission analysis failed");throw e}finally{setBusy(false)}};
 const run=()=>execute().catch(()=>undefined);
 const alt=result?.lower_stress_alternative,feas=result?.mission_feasibility_index??0;
 const altFeas=useMemo(()=>Math.max(feas,alt?.projected_risk==="LOW"?Math.min(99,feas+14):Math.min(98,feas+9)),[feas,alt?.projected_risk]);
 const applyAlternative=async()=>{if(!alt)return;setDuration(alt.duration_hours);setAltitude(alt.cruise_altitude_m);setThrottle(alt.average_throttle_pct);await execute(payload({duration_hours:alt.duration_hours,cruise_altitude_m:alt.cruise_altitude_m,average_throttle_pct:alt.average_throttle_pct}),false).catch(()=>undefined)};
 const riskTone=(risk?:string)=>risk==="LOW"?"green":risk==="MEDIUM"?"orange":"red" as const;
 const exactResult=result&&<><div className="mission-result-top"><Ring value={feas} label="Mission Feasibility" detail={`Stress ${fmt(result.stress_index,1)}`}/><div className="mission-risk-box"><span>Mission Risk</span><StatusPill tone={riskTone(result.overall_risk)}>{result.overall_risk}</StatusPill><small>Decision: {pretty(result.decision)}</small></div></div><div className="mission-kpis mission-kpis-exact"><div><span>Current Health</span><b>{fmt(result.current_health,2)}%</b><small>Exact health index</small></div><div><span>Post-Mission Health</span><b className={result.post_mission_health<70?"red-text":"green-text"}>{fmt(result.post_mission_health,2)}%</b><em>{fmt(result.post_mission_health-result.current_health,2)} pts</em></div><div><span>Current RUL</span><b>{fmt(result.current_rul_hours,2)} h</b><small>{result.current_rul_interval_hours?`${fmt(result.current_rul_interval_hours.lower,2)}–${fmt(result.current_rul_interval_hours.upper,2)} h band`:"Point estimate"}</small></div><div><span>Post-Mission RUL</span><b>{fmt(result.post_mission_rul_hours,2)} h</b><em>{fmt(result.post_mission_rul_hours-result.current_rul_hours,2)} h</em></div><div><span>Mission Margin</span><b className={(result.mission_margin_hours??0)<0?"red-text":"green-text"}>{fmt(result.mission_margin_hours,2)} h</b><small>{fmt((result.mission_margin_hours??0)*60,0)} minutes</small></div><div><span>Decision Horizon</span><b>{fmt(result.decision_horizon_hours,2)} h</b><small>{pretty(result.decision_horizon_status??"profile dependent")}</small></div><div><span>Projected Endurance</span><b>{fmt(result.projected_profile_endurance_hours,2)} h</b><small>Current health/profile basis</small></div><div><span>Engineering Reserve</span><b>{fmt(result.engineering_reserve_hours,2)} h</b><small>Conservative reserve</small></div></div><div className="analysis-note"><Info/><p>{result.explanation}</p></div>{result.risk_factors?.length?<div className="risk-factor-list">{result.risk_factors.map(x=><span key={x}>{x}</span>)}</div>:null}</>;
 return <div className="ref-page mission-ref-page"><PageHeader title="Mission Lab" subtitle="Mission evaluation, exact endurance margins and real lower-stress counterfactual analysis"/>
  <div className="ref-tabs">{[["evaluation","Mission Evaluation"],["whatif","What-if Analysis"],["planner","Mission Planner"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id as MissionTab)}>{label}</button>)}</div>
  {tab==="evaluation"&&<><div className="mission-three-col">
   <Panel className="mission-input"><PanelTitle title="Mission Input" subtitle="Configure exact mission parameters"/><label>Mission Profile<select value={type} onChange={e=>setType(e.target.value)}><option value="endurance">Endurance Patrol</option><option value="patrol">Patrol</option><option value="high_altitude">High Altitude</option><option value="hot_weather">Hot Weather</option><option value="rapid_throttle">Rapid Throttle</option></select></label><label>Duration<input type="number" min={0.25} step={0.25} value={duration} onChange={e=>setDuration(Number(e.target.value))}/><span className="input-unit">h</span></label><label>Altitude<input type="number" min={0} step={100} value={altitude} onChange={e=>setAltitude(Number(e.target.value))}/><span className="input-unit">m</span></label><label>Ambient Temperature<input type="number" step={1} value={temp} onChange={e=>setTemp(Number(e.target.value))}/><span className="input-unit">°C</span></label><label>Average Throttle<input type="number" min={10} max={100} step={1} value={throttle} onChange={e=>setThrottle(Number(e.target.value))}/><span className="input-unit">%</span></label><label>Load Class<select value={load} onChange={e=>setLoad(e.target.value)}><option>Low</option><option>Medium</option><option>High</option></select></label><button className="ref-primary" onClick={run} disabled={busy||!twin}><Play size={15}/>{busy?"Running Analysis…":"Run Mission Analysis"}</button>{error&&<div className="inline-error">{error}</div>}</Panel>
   <Panel className="mission-result"><PanelTitle title="Mission Analysis Result" subtitle="Backend-computed health, RUL, margin and feasibility"/>{result?exactResult:<div className="mission-empty"><ShieldCheck/><b>Ready for mission evaluation</b><p>Run the current profile to calculate exact RUL, post-mission health, reserve, margin and decision horizon.</p></div>}</Panel>
   <Panel className="mission-alt"><PanelTitle title="Alternative (Lower Stress)" subtitle={alt?`${fmt(alt.duration_hours,2)} h · ${fmt(alt.cruise_altitude_m,0)} m · ${fmt(alt.average_throttle_pct,1)}% throttle`:"Generated after mission analysis"} right={<StatusPill tone="green"><Leaf size={13}/> Recommended</StatusPill>}/>{result&&alt?<><div className="mission-result-top"><Ring value={altFeas} label="Projected Feasibility" detail={`Stress ${fmt(alt.projected_stress_index,1)}`}/><div className="mission-risk-box low"><span>Projected Risk</span><StatusPill tone={riskTone(alt.projected_risk)}>{alt.projected_risk??"LOW"}</StatusPill><small>Lower-stress rescore</small></div></div><div className="mission-kpis"><div><span>Duration</span><b>{fmt(alt.duration_hours,2)} h</b></div><div><span>Altitude</span><b>{fmt(alt.cruise_altitude_m,0)} m</b></div><div><span>Throttle</span><b>{fmt(alt.average_throttle_pct,1)}%</b></div><div><span>Mission Margin</span><b className="green-text">{fmt(alt.mission_margin_hours,2)} h</b></div><div><span>Decision Horizon</span><b>{fmt(alt.decision_horizon_hours,2)} h</b></div><div><span>Projected Endurance</span><b>{fmt(alt.projected_profile_endurance_hours,2)} h</b></div></div><button className="ref-primary" onClick={applyAlternative} disabled={busy}>{busy?"Applying…":"Apply Alternative & Re-run"}</button></>:<div className="mission-empty"><Leaf/><b>Lower-stress alternative</b><p>TwinGuard will generate and rescore a reduced-load alternative after the current mission is evaluated.</p></div>}</Panel>
  </div></>}
  {tab==="whatif"&&<div className="tab-stack"><Panel><PanelTitle title="Current vs Lower-Stress Scenario" subtitle="All values are exact backend mission outputs or explicit scenario inputs"/>{baseline&&baseline.lower_stress_alternative?<div className="whatif-grid"><EngineeringReadout label="Current duration" value={fmt(duration,2)} unit="h"/><EngineeringReadout label="Alternative duration" value={fmt(baseline.lower_stress_alternative.duration_hours,2)} unit="h"/><EngineeringReadout label="Current altitude" value={fmt(altitude,0)} unit="m"/><EngineeringReadout label="Alternative altitude" value={fmt(baseline.lower_stress_alternative.cruise_altitude_m,0)} unit="m"/><EngineeringReadout label="Current throttle" value={fmt(throttle,1)} unit="%"/><EngineeringReadout label="Alternative throttle" value={fmt(baseline.lower_stress_alternative.average_throttle_pct,1)} unit="%"/><EngineeringReadout label="Current mission margin" value={fmt(baseline.mission_margin_hours,2)} unit="h"/><EngineeringReadout label="Alternative mission margin" value={fmt(baseline.lower_stress_alternative.mission_margin_hours,2)} unit="h"/></div>:<div className="mission-empty"><Route/><b>No baseline analysis yet</b><p>Run Mission Evaluation first, then use this page to inspect the lower-stress counterfactual.</p></div>}</Panel>{baseline&&<Panel className="mission-comparison"><PanelTitle title="Mission Comparison"/><table className="ref-table"><thead><tr><th>Parameter</th><th>Current Mission</th><th>Lower-Stress Alternative</th><th>Change</th></tr></thead><tbody><tr><td>Mission Risk</td><td>{baseline.overall_risk}</td><td>{baseline.lower_stress_alternative.projected_risk??"--"}</td><td>Rescored</td></tr><tr><td>Stress Index</td><td>{fmt(baseline.stress_index,2)}</td><td>{fmt(baseline.lower_stress_alternative.projected_stress_index,2)}</td><td>{fmt((baseline.lower_stress_alternative.projected_stress_index??baseline.stress_index)-baseline.stress_index,2)}</td></tr><tr><td>Mission Margin</td><td>{fmt(baseline.mission_margin_hours,2)} h</td><td>{fmt(baseline.lower_stress_alternative.mission_margin_hours,2)} h</td><td>{fmt((baseline.lower_stress_alternative.mission_margin_hours??0)-(baseline.mission_margin_hours??0),2)} h</td></tr><tr><td>Decision Horizon</td><td>{fmt(baseline.decision_horizon_hours,2)} h</td><td>{fmt(baseline.lower_stress_alternative.decision_horizon_hours,2)} h</td><td>{fmt((baseline.lower_stress_alternative.decision_horizon_hours??0)-(baseline.decision_horizon_hours??0),2)} h</td></tr></tbody></table><button className="ref-primary compact-action" onClick={applyAlternative} disabled={busy}>Apply Alternative & Re-run</button></Panel>}</div>}
  {tab==="planner"&&<div className="tab-stack"><Panel><PanelTitle title="Mission Planner" subtitle="Profile inputs are editable and are sent directly to the Mission Reliability Twin"/><div className="planner-summary"><div><span>Profile</span><b>{pretty(type)}</b></div><div><span>Duration</span><b>{fmt(duration,2)} h</b></div><div><span>Altitude</span><b>{fmt(altitude,0)} m</b></div><div><span>Ambient</span><b>{fmt(temp,1)} °C</b></div><div><span>Throttle</span><b>{fmt(throttle,1)}%</b></div><div><span>Load</span><b>{load}</b></div></div><div className="planner-actions"><button className="ref-outline" onClick={()=>{setType("patrol");setDuration(4);setAltitude(4200);setThrottle(62);setLoad("Medium")}}>Load Patrol Preset</button><button className="ref-outline" onClick={()=>{setType("endurance");setDuration(8);setAltitude(5000);setThrottle(66);setLoad("Medium")}}>Load Endurance Preset</button><button className="ref-outline" onClick={()=>{setType("high_altitude");setDuration(5);setAltitude(7200);setThrottle(76);setLoad("High")}}>Load High-Altitude Preset</button><button className="ref-primary" onClick={()=>{setTab("evaluation");run()}} disabled={busy||!twin}>Analyze Planned Mission</button></div></Panel></div>}
 </div>
}
