import type{ReactNode}from"react";
import{Plane,Activity}from"lucide-react";
import{fmt}from"./ui";

export function PageHeader({title,subtitle}:{title:string;subtitle:string}){return <div className="ref-page-head"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="ref-asset-chip"><Plane size={27}/><strong>ENGINE-01</strong><span><b>MALE-class UAV</b> · Prototype 1<small>Medium-altitude long-endurance platform</small></span></div></div>}
export function Panel({children,className=""}:{children:ReactNode;className?:string}){return <section className={`ref-panel ${className}`}>{children}</section>}
export function PanelTitle({icon,title,subtitle,right}:{icon?:ReactNode;title:string;subtitle?:string;right?:ReactNode}){return <div className="ref-panel-title"><div className="ref-panel-title-main">{icon}<div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{right}</div>}
export function Ring({value,label,delta,detail}:{value:number;label:string;delta?:string;detail?:string}){const v=Math.max(0,Math.min(100,value));return <div className="ref-ring-wrap"><div className="ref-ring" style={{background:`conic-gradient(${v<70?"#ff3b30":v<86?"#18a0fb":"#08b85c"} ${v*3.6}deg,#e4eef7 0)`}}><div><b>{Math.round(v)}%</b>{delta&&<em>{delta}</em>}</div></div><span>{label}</span>{detail&&<small className="ring-detail">{detail}</small>}</div>}
export function Bar({value,color="green"}:{value:number;color?:"green"|"blue"|"orange"|"red"}){return <div className={`ref-bar ${color}`}><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
export function StatusPill({children,tone="green"}:{children:ReactNode;tone?:"green"|"orange"|"red"|"blue"}){return <span className={`ref-pill ${tone}`}>{children}</span>}
export function MetricCard({icon,label,value,unit,quality=92,precision,expected,delta,helper}:{icon:ReactNode;label:string;value:number|string;unit?:string;quality?:number;precision?:number;expected?:string;delta?:string;helper?:string}){const d=precision??(label==="Vibration"?3:label.includes("Flow")||label.includes("Voltage")?2:label.includes("Temp")||label==="CHT"||label==="EGT"?1:0);return <div className="ref-metric"><div className="ref-metric-label">{icon}<span>{label}</span></div><div className="ref-metric-value"><b>{typeof value==="number"?fmt(value,d):value}</b>{unit&&<small>{unit}</small>}<span className="ref-signal">{[0,1,2,3,4].map((x,i)=><i key={i} style={{height:`${5+i*3}px`,opacity:quality/100}}/>)}</span></div>{(expected||delta||helper)&&<div className="ref-metric-meta">{expected&&<span>Expected <b>{expected}</b></span>}{delta&&<span>Δ <b>{delta}</b></span>}{helper&&<span>{helper}</span>}</div>}</div>}
export function EngineeringReadout({label,value,unit,expected,residual,tone="blue"}:{label:string;value:string;unit?:string;expected?:string;residual?:string;tone?:"blue"|"green"|"orange"|"red"}){return <div className={`engineering-readout ${tone}`}><span>{label}</span><div><b>{value}</b>{unit&&<small>{unit}</small>}</div>{(expected||residual)&&<p>{expected&&<>Expected <strong>{expected}</strong></>}{residual&&<> · Residual <strong>{residual}</strong></>}</p>}</div>}
export function MiniLineChart({series,labels}:{series:Array<{name:string;values:number[];color:string}>;labels?:string[]}){const width=720,height=210,pad=24,all=series.flatMap(s=>s.values),min=Math.min(...(all.length?all:[0])),max=Math.max(...(all.length?all:[1])),span=max-min||1;const pts=(values:number[])=>values.map((v,i)=>`${pad+(i/Math.max(1,values.length-1))*(width-pad*2)},${height-pad-((v-min)/span)*(height-pad*2)}`).join(" ");return <div className="ref-chart"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><g className="grid">{[0,1,2,3,4].map(i=><line key={`h${i}`} x1={pad} y1={pad+i*(height-pad*2)/4} x2={width-pad} y2={pad+i*(height-pad*2)/4}/>)}{[0,1,2,3,4,5,6].map(i=><line key={`v${i}`} y1={pad} x1={pad+i*(width-pad*2)/6} y2={height-pad} x2={pad+i*(width-pad*2)/6}/>)}</g>{series.map(s=><polyline key={s.name} points={pts(s.values.length?s.values:[0,0])} fill="none" stroke={s.color} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/>)}</svg><div className="ref-chart-legend">{series.map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}</span>)}</div>{labels&&<div className="ref-chart-labels">{labels.map(x=><span key={x}>{x}</span>)}</div>}</div>}
export function EmptyState({text}:{text:string}){return <div className="ref-empty"><Activity size={26}/><span>{text}</span></div>}
