import{CircleStop,Pause,Play,RotateCcw,SkipForward}from"lucide-react";
import{useEffect,useMemo,useState}from"react";
import{endReplay,getReplay,listReplay,startReplay}from"../services/twinApi";
import{useTwinStore}from"../store/twinStore";
import type{ReplayMission}from"../types/twin";
import{fmt}from"./ui";
import{EngineeringReadout,MiniLineChart,PageHeader,Panel,PanelTitle}from"./ReferenceUI";

export default function ReplayDeck(){
 const history=useTwinStore(s=>s.history),missions=useTwinStore(s=>s.missions),setMissions=useTwinStore(s=>s.setMissions),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[speed,setSpeed]=useState(1),[selected,setSelected]=useState<ReplayMission>();
 useEffect(()=>{listReplay().then(m=>{setMissions(m);if(m[0])setSelected(m[0])}).catch(()=>undefined)},[setMissions]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setProgress(v=>Math.min(100,v+.18*speed)),250);return()=>clearInterval(id)},[playing,speed]);
 useEffect(()=>{if(progress>=100)setPlaying(false)},[progress]);
 const start=async()=>{setBusy(true);try{const m=await startReplay(`TwinGuard Mission ${new Date().toLocaleString()}`);setRecording(true);setSelected(m);setProgress(0)}finally{setBusy(false)}},stop=async()=>{setBusy(true);try{const m=await endReplay();setRecording(false);const all=await listReplay();setMissions(all);setSelected(all.find(x=>x.id===m.id)??m);setProgress(100)}finally{setBusy(false)}};
 const choose=async(id:number)=>{setBusy(true);try{const m=await getReplay(id);setSelected(m);setProgress(0);setPlaying(false)}finally{setBusy(false)}};
 const summary=(selected?.summary??{}) as Record<string,any>,events=(summary.events??[]) as Array<Record<string,any>>,durationSeconds=Number(summary.duration_seconds??summary.elapsed_seconds??28800),elapsed=Math.round(progress/100*durationSeconds);
 const formatTime=(s:number)=>`${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor((s%3600)/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}`;
 const markerEvents=events.length?events.slice(0,10):[{type:"Live telemetry synchronized",timestamp:selected?.started_at??new Date().toISOString(),severity:"blue",message:"Replay event data will appear here as mission recording events are stored."}];
 const trim=(a:number[])=>a.slice(-90),currentIndex=Math.max(0,Math.min(89,Math.round(progress/100*89))),at=(key:string)=>Number((history[key]??[])[Math.min(currentIndex,(history[key]??[]).length-1)]??0);
 return <div className="ref-page replay-ref-page"><PageHeader title="Mission Replay" subtitle="Functional playback, recorded missions, synchronized telemetry and exact event inspection"/>
  <div className="replay-controls-row"><Panel className="replay-controls"><PanelTitle title="Playback Controls" right={<select value={selected?.id??""} onChange={e=>choose(Number(e.target.value))} disabled={busy}><option value="">Select recording</option>{missions.map(m=><option value={m.id} key={m.id}>#{m.id} · {m.label}</option>)}</select>}/><div className="player-controls"><button title="Play" onClick={()=>setPlaying(true)} disabled={!selected&&missions.length>0}><Play/></button><button title="Pause" onClick={()=>setPlaying(false)}><Pause/></button><button title="Skip forward 10%" onClick={()=>setProgress(v=>Math.min(100,v+10))}><SkipForward/></button><button title="Restart" onClick={()=>{setProgress(0);setPlaying(false)}}><RotateCcw/></button><input className="replay-range" type="range" min="0" max="100" step="0.1" value={progress} onChange={e=>{setProgress(Number(e.target.value));setPlaying(false)}}/><strong>{formatTime(elapsed)} / {formatTime(durationSeconds)}</strong><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={0.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select><button className="record-btn" disabled={busy||recording} onClick={start}>{busy?"Working…":"Record"}</button><button className="stop-btn" disabled={busy||!recording} onClick={stop}><CircleStop size={14}/> End</button></div></Panel>
   <Panel><PanelTitle title="Recording Status"/><div className="replay-status-grid"><div><span>Recording</span><b className={recording?"red-text":"green-text"}>{recording?"ACTIVE":"IDLE"}</b></div><div><span>Saved missions</span><b>{missions.length}</b></div><div><span>Playback</span><b>{fmt(progress,1)}%</b></div></div></Panel>
  </div>
  <Panel><PanelTitle title="Playback Engineering Snapshot" subtitle="Exact values at the selected playback position"/><div className="engineering-grid"><EngineeringReadout label="RPM" value={fmt(at("rpm"),0)} unit="rpm"/><EngineeringReadout label="Oil Pressure" value={fmt(at("oil_pressure")*100,1)} unit="kPa"/><EngineeringReadout label="Oil Temperature" value={fmt(at("oil_temperature"),1)} unit="°C"/><EngineeringReadout label="CHT" value={fmt(at("cht"),1)} unit="°C"/><EngineeringReadout label="EGT" value={fmt(at("egt"),1)} unit="°C"/><EngineeringReadout label="Vibration" value={fmt(at("vibration"),3)} unit="g"/></div></Panel>
  <div className="replay-main-grid">
   <Panel><PanelTitle title="Telemetry Timeline"/><div className="stacked-charts"><div><b>RPM<br/><small>(rpm)</small></b><MiniLineChart series={[{name:"RPM",values:trim(history.rpm??[]),color:"#1479f8"}]}/></div><div><b>Oil Pressure<br/><small>(kPa)</small></b><MiniLineChart series={[{name:"Oil Pressure",values:trim(history.oil_pressure??[]).map(v=>v*100),color:"#ff3a36"}]}/></div><div><b>Oil Temp<br/><small>(°C)</small></b><MiniLineChart series={[{name:"Oil Temp",values:trim(history.oil_temperature??[]),color:"#ff7a00"}]}/></div><div><b>Vibration<br/><small>(g)</small></b><MiniLineChart series={[{name:"Vibration",values:trim(history.vibration??[]),color:"#8a38eb"}]}/></div></div></Panel>
   <Panel><PanelTitle title="Event Details" subtitle={selected?`${selected.label} · ${selected.status}`:"No stored recording selected"}/><div className="event-details">{markerEvents.map((e,i)=><div key={i}><i className={String(e.severity??["red","orange","purple","blue","green","gray"][i%6])}/><div><time>{String(e.timestamp??"").slice(-8)||`event ${i+1}`}</time><b>{String(e.type??e.message??"Event")}</b><p>{String(e.message??"Recorded TwinGuard mission event")}</p></div></div>)}</div></Panel>
  </div>
 </div>
}
