import{Database,Download,Info,RefreshCcw,Server,ShieldCheck,SlidersHorizontal,Trash2,UserRound}from"lucide-react";
import{useEffect,useState}from"react";
import{getSystemStatus,resetFault,setFault}from"../services/twinApi";
import{useTwinStore}from"../store/twinStore";
import type{FaultName,SystemStatus}from"../types/twin";
import{pretty}from"./ui";
import{PageHeader,Panel,PanelTitle,StatusPill}from"./ReferenceUI";

export default function SettingsDeck(){
 const twin=useTwinStore(s=>s.twin),runtime=useTwinStore(s=>s.runtimeValidity),[status,setStatus]=useState<SystemStatus>(),[scenario,setScenario]=useState<FaultName>("normal"),[severity,setSeverity]=useState(0),[freshness,setFreshness]=useState(5),[mode,setMode]=useState("Hybrid (Physics + AI)");
 const load=()=>getSystemStatus().then(setStatus).catch(()=>setStatus(undefined));useEffect(()=>{load()},[]);
 const applyScenario=async()=>{if(scenario==="normal")await resetFault();else await setFault(scenario,severity/100)};
 const exportData=(type:"csv"|"json")=>{const data=twin??{};const text=type==="json"?JSON.stringify(data,null,2):Object.entries(twin?.telemetry??{}).map(([k,v])=>`${k},${v}`).join("\n");const blob=new Blob([text],{type:type==="json"?"application/json":"text/csv"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`twinguard-telemetry.${type}`;a.click();URL.revokeObjectURL(url)};
 return <div className="ref-page settings-ref-page"><PageHeader title="Settings & System" subtitle="Configure system settings, connections, simulation, models, and data management"/>
  <div className="ref-tabs settings-tabs"><button className="active">System</button><button>Connections</button><button>Simulator</button><button>Model Configuration</button><button>Data Management</button><button>User</button></div>
  <div className="system-status-cards">{[["Backend",status?.service?"Connected":"Waiting",Server,"green"],["Simulator","Running",RefreshCcw,"green"],["Database",status?.database??"Connected",Database,"green"],["Model Runtime",pretty(twin?.ai.model_state??"Engineering Fallback"),SlidersHorizontal,"blue"],["Data Validity",`${Math.round(Number(runtime?.data_quality??twin?.confidence.data_quality??98))}%`,ShieldCheck,"green"],["System Version",status?.version??"v2.1.0",Info,"blue"],["Environment",pretty(status?.environment??"Development"),UserRound,"orange"]].map(([k,v,Icon,tone]:any)=><div className="system-status-card" key={k}><Icon/><span>{k}</span><b className={`${tone}-text`}>● {v}</b></div>)}</div>
  <div className="settings-columns">
   <Panel><PanelTitle title="Connection Settings" subtitle="Configure API and WebSocket connections to engine systems and simulator."/><label>API URL<input value="http://localhost:8000" readOnly/></label><label>WebSocket URL<input value="ws://localhost:8000/ws" readOnly/></label><div className="connection-ok"><b>● Connected</b><p>All systems reachable. Real-time data stream active.</p></div></Panel>
   <Panel><PanelTitle title="Simulator Controls" subtitle="Control simulation parameters and fault injection for testing."/><label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value as FaultName)}><option value="normal">Healthy</option><option value="lubrication">Lubrication Degradation</option><option value="overheating">Overheating</option><option value="cooling_degradation">Cooling Degradation</option><option value="vibration">Abnormal Vibration</option><option value="sensor_drift">Sensor Drift</option><option value="injector">Injector Abnormality</option><option value="misfire">Misfire</option><option value="combustion_instability">Combustion Instability</option><option value="alternator_degradation">Alternator Degradation</option></select></label><label>Fault Intensity <b>{severity}%</b><input type="range" min="0" max="100" value={severity} onChange={e=>setSeverity(Number(e.target.value))}/></label><div className="switch-row"><span>Auto Reset</span><button className="fake-switch active"><i/></button></div><button className="ref-outline" onClick={applyScenario}><RefreshCcw size={15}/>Apply / Reset Simulator</button></Panel>
   <Panel><PanelTitle title="Runtime Configuration" subtitle="Configure data processing and model runtime parameters."/><label>Telemetry Freshness Threshold<select value={freshness} onChange={e=>setFreshness(Number(e.target.value))}><option value={3}>3 seconds</option><option value={5}>5 seconds</option><option value={10}>10 seconds</option></select></label><label>Ingest Mode<select><option>Live + Simulator</option><option>Live Only</option><option>Simulator Only</option></select></label><label>Model Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>Hybrid (Physics + AI)</option><option>Engineering Fallback</option><option>Native ML</option></select></label><div className="settings-info"><Info/><p>Runtime selections are UI configuration controls for the demonstrator; engine-specific validation remains required.</p></div><button className="ref-primary">Save Configuration</button></Panel>
   <Panel><PanelTitle title="Data Management" subtitle="Manage telemetry data, model sessions and local storage."/><button className="settings-action" onClick={()=>exportData("csv")}><Download/>Export Telemetry (CSV)</button><button className="settings-action" onClick={()=>exportData("json")}><Download/>Export Session (JSON)</button><button className="settings-action danger"><Trash2/>Clear Local Data</button><div className="settings-info"><Info/><p>Clearing local data removes cached browser state. Backend mission records remain separately managed.</p></div></Panel>
   <Panel className="about-panel"><PanelTitle title="About TwinGuard" subtitle="System information and build details."/><div className="about-brand"><img src="/assets/twinguard-mark.svg"/><div><b>TwinGuard AI</b><span>Mission Reliability. Assured.</span></div></div><div className="about-list"><div><span>Version:</span><b>{status?.version??"v2.1.0"}</b></div><div><span>Engine:</span><b>Aero-Piston (MALE UAV)</b></div><div><span>Built for:</span><b>SIH 2026 (DRDO)</b></div><div><span>Developer:</span><b>Krishna Tayal & Team</b></div></div><div className="about-art"><span>✈</span><b>BUILT FOR SAFER SKIES</b><small>MONITOR · PREDICT · DECIDE · COMPLETE</small></div></Panel>
  </div>
 </div>
}
