import{motion}from"framer-motion";import type{CSSProperties,ReactNode}from"react";
export const fmt=(v:unknown,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"--",pct=(v:unknown)=>`${Math.round(Math.max(0,Math.min(100,Number(v)||0)))}%`,pretty=(s:unknown)=>String(s??"").replace(/_/g," ").replace(/\b\w/g,(c:string)=>c.toUpperCase()),tone=(v:number,good=88,warn=70)=>v>=good?"good":v>=warn?"warn":"bad";
export function Card({children,className=""}:{children:ReactNode;className?:string}){return <motion.section className={`card ${className}`} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.32}}>{children}</motion.section>}
export function SectionTitle({eyebrow,title,action}:{eyebrow:string;title:string;action?:ReactNode}){return <div className="section-title"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</div>}
export function Badge({children,kind="neutral"}:{children:ReactNode;kind?:"good"|"warn"|"bad"|"neutral"|"blue"}){return <span className={`badge ${kind}`}>{children}</span>}
export function Progress({value,kind="blue"}:{value:number;kind?:"blue"|"good"|"warn"|"bad"}){return <div className={`progress ${kind}`}><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
export function MiniSpark({values}:{values:number[]}){const a=values.length?values:[0,0],min=Math.min(...a),max=Math.max(...a),span=max-min||1,pts=a.map((v,i)=>`${(i/(a.length-1||1))*100},${34-((v-min)/span)*26}`).join(" ");return <svg viewBox="0 0 100 38" preserveAspectRatio="none" className="spark"><polyline points={pts} fill="none" vectorEffect="non-scaling-stroke"/></svg>}
export function Ring({value,label,toneName="good"}:{value:number;label:string;toneName?:"good"|"warn"|"bad"}){return <div className={`ring ${toneName}`} style={{"--ring-value":`${Math.max(0,Math.min(100,value))*3.6}deg`} as CSSProperties}><div><strong>{pct(value)}</strong><span>{label}</span></div></div>}
export const download=(name:string,data:string,type:string)=>{const b=new Blob([data],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)};
